### PR TITLE
Add support for 32-bit releases

### PR DESCRIPTION
**Pull request by G-flat**
Allow both 32-bit and 64-bit releases to be made.

This is done to make the game more accessible to a wider audience. Although the vast majority of computer users now use 64-bit computers, there are some users that play with 32-bit computers.

### CODE REVIEW

**Review by Zageron — CHANGES_REQUESTED** [review]
I wonder if we can generate a release string and look for it before creating one for both workflows. Having two separate releases for 32vs64 is kinda verbose, rather than just one release and multiple artifacts.

**Comment by G-flat** [comment]
Does that mean you want to keep the two release workflows into one if possible? It definitely is better to keep everything in one place for this scenario. I could try working on that.

**Comment by G-flat** [comment]
I've made some changes to the workflow files. Please review them.

I'm not sure if I have to build the fonts separately for 32-bit and 64-bit releases.

**Review by Zageron — APPROVED** [review]

**Comment by Zageron** [comment]
Before submission, test this by adding a tag to it and see how the workflow handles building the tagged release.

**Comment by G-flat** [comment]
Tested the tagged release, everything seems fine. PR should be good to go.

**Review by Zageron — APPROVED** [review]

**Pull request merged**
