### PR TITLE
Add Additional Combo Color Options

### PR DESCRIPTION
**Pull request by Xyr00**
Change gives additional combo color functionality and options to set those.

Changes:
Updated comboColour array (User.as)
Updated comboColour array defaults (GameOptions.as)
Updated combo color logic (Combo.as); also includes update to GamePlay.as to pass gameRawGoods var to Combo.as
Updated settings menu to swap columns for game color & combo color to better fit new options (PopupOptions.as)
Added a check to merge existing comboColors with system default if sizes of arrays were different to prevent crash (User.as)

image

Remaining updates:
1. Add "options_combo_colors_3" through "options_combo_colors_6" to language editor files
a. SDG
b. Black Flag
c. Average Flag
d. Boo Flag

### CODE REVIEW

**Comment by Xyr00** [comment]
Chose SDG default color as transition from AAA (gold) -> FC (dark green)
Chose Blackflag default as grey since black background on most files
Chose Avflag color because it's the default of Average judge color
Chose Booflag color as a lighter variant of default Boo judge color

**Comment by maxproske** [comment]
I'm so glad someone is finally expanding the combo colours! :)

I'm just imagining how confusing this could be for new players, who aren't going for AAA's and will see the first note flash a different colour, seemingly at random. ITG solves this by having a "PercentUntilColorCombo" constant. Hey maybe I'm making a big deal about nothing.

Language constants ending in _1, _2, etc. could be more descriptive (_bf, _sdg)?

**Comment by Psycast** [comment]
> Language constants ending in _1, _2, etc. could be more descriptive (_bf, _sdg)?

The language constants given follow the current pattern as the options are built from an array with int indexes.
Changing them to be more descriptive would add extra work with no real benefit as it's never show to the user, nor are they printed directly in code, just created in the loop.

**Comment by Xyr00** [comment]
Agreed regarding language constants.

> I'm just imagining how confusing this could be for new players, who aren't going for AAA's and will see the first note flash a different colour, seemingly at random. ITG solves this by having a "PercentUntilColorCombo" constant.

I could see some potential benefit to this suggestion, but what level of assumption do we make that a user doesn't want to know their PA against the combo color from x% of the song? I guess ultimately I'd be curious to explore this more, but seeing those colors might lead to them exploring the menu options earlier on as well.

**Comment by G-flat** [comment]
@all-contributors please add @Xyr00 for ideas

**Pull request merged**
