### PR TITLE
Invalid Settings - Example

### LINKED ISSUE #10: Add UI feedback for improper values
**Overview**
Users get no feedback for invalid options throughout the game; values that may be perceived as valid are instead reset to defaults without any indication that the game has deemed them as invalid.

**Suggestion**
Highlight UI elements containing type-valid values whose setting falls outside of the threshold before resetting to a default. I attempted to add text underneath the erroneous values but quickly realized that space was too limited to provide anything meaningful. An additional hoverable icon indicator can be added to tell them what the issue is.

**Images**
https://i.imgur.com/WG510Bf.png -- note that in this image, the two values highlighted are actually values that will cause the game to revert to the default of 1. That is: scroll speeds less than or equal to 0.1 will reset to 1, and song rates less than 0.1 will reset to 1 as well. There may be others.

### PR DESCRIPTION
**Pull request by Zageron**
Just did a quick example of what we could do for visual feedback on the box.
Resolves #10 

image

### CODE REVIEW

**Comment by Xyr00** [comment]
Would it be possible to have a red tint to the textbox background as well? I feel that would bring more attention to the fact it's invalid than just the border.

**Comment by Zageron** [comment]
> 
> 
> Would it be possible to have a red tint to the textbox background as well? I feel that would bring more attention to the fact it's invalid than just the border.

It does, so I can change the opacity of the background colour.

**Comment by Xyr00** [comment]
image

Current state with changes I've made to code locally - feedback welcome, is this too aggressive?

The next/last step will be finalizing all validation for fields, which is not a strong point for me.

**Comment by Zageron** [comment]
> 
> 
> image
> 
> Current state with changes I've made to code locally - feedback welcome, is this too aggressive?
> 
> The next/last step will be finalizing all validation for fields, which is not a strong point for me.

@TCHalogen How's this version look? #10

**Comment by TCHalogen** [comment]
> > image
> > Current state with changes I've made to code locally - feedback welcome, is this too aggressive?
> > The next/last step will be finalizing all validation for fields, which is not a strong point for me.
> 
> @TCHalogen How's this version look? #10

That looks good; is this PR to check for the entirety of the functionality, or just the appearance of it?

**Comment by Xyr00** [comment]
I believe appearance to start, functionality to follow. All my changes were specifically were to appearance.

**Comment by Zageron** [comment]
@TCHalogen Just to check on the appearance. I'll go through some more of the fields soon and set them up with visual validity feedback.

**Comment by Psycast** [comment]
An implementation of this was included in #218.

**Pull request closed without merging**
